trigger:
  branches:
    exclude:
      - main
  paths:
    include:
      - '**/*.bim'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.bim'

pool:
  vmImage: 'windows-latest'

stages:
 - stage: Build
   jobs:

    - job: Build_Datasets
      steps:
        - checkout: self
          path: 'self'
        - task: PowerShell@2
          displayName: 'Download Tabular Editor and Default Rules'
          inputs:
            targetType: inline
            script: |     
              $path = "$(Build.SourcesDirectory)"                       
              $tempPath = "$path\_temp"
              $toolPath = "$path\_tools\TE"
              New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null              
              
              Write-Host "##[debug]Downloading Tabular Editor binaries"
              $downloadUrl = "https://github.com/TabularEditor/TabularEditor/releases/latest/download/TabularEditor.Portable.zip"
              $zipFile = "$tempPath\TabularEditor.zip"
              Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
              Expand-Archive -Path $zipFile -DestinationPath $toolPath -Force   

        - task: PowerShell@2
          displayName: 'Run Dataset Rules'
          inputs:
            targetType: inline
            script: |
              $path = "$(Build.SourcesDirectory)"
              $tempPath = "$path\_temp"
              $toolPath = "$path\_Tools\TE\TabularEditor.exe"
              
              # CHANGED HERE: pointing to your custom rules
              $rulesPath = "$path\bpa_custom_rules\bpa_rules_high_severity.json"

              if (!(Test-Path $rulesPath))
              {
                  Write-Host "Running downloaded rules"
                  $rulesPath = "$tempPath\Rules-Dataset.json"
              }

              $itemsFolders = Get-ChildItem -Path $path -Recurse -Include ("*.pbidataset", "*.pbism")

              foreach($itemFolder in $itemsFolders)
              {	
                  $itemPath = "$($itemFolder.Directory.FullName)\definition"

                  if (!(Test-Path $itemPath))
                  {
                      $itemPath = "$($itemFolder.Directory.FullName)\model.bim"

                      if (!(Test-Path $itemPath))
                      {
                          throw "Cannot find semantic model definition."
                      }
                  }

                  Write-Host "##[group]Running rules for: '$itemPath'"

                  Start-Process -FilePath "$toolPath" -ArgumentList """$itemPath"" -A ""$rulesPath"" -V" -NoNewWindow -Wait

                  Write-Host "##[endgroup]"
              }
