trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**/report.json'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build and Inspect Reports'
  jobs:
  - job: Build_Reports
    displayName: 'Inspect Modified Reports'
    steps:
      # 1) Checkout the repository with full history.
      - checkout: self
        path: 'self'
        persistCredentials: true
        fetchDepth: 0

      # 2) Identify modified report.json files by comparing HEAD to origin/main.
      - task: PowerShell@2
        displayName: 'Identify modified report.json files'
        inputs:
          targetType: inline
          script: |
            cd "$(Build.SourcesDirectory)"
            Write-Host "##[section]Comparing HEAD with origin/main to find changed report.json files..."
            git fetch --all
            $changedFiles = git diff --name-only HEAD origin/main
            $filteredFiles = $changedFiles | Where-Object { $_ -like '*report.json' }
            if ($filteredFiles) {
              Write-Host "##[section]Found modified report.json files in this PR:"
              $filteredFiles | ForEach-Object { Write-Host " - $_" }
              $reportFiles = $filteredFiles | Sort-Object -Unique
              Write-Host "##[section]Reports to inspect: $($reportFiles -join ';')"
              Write-Host "##vso[task.setvariable variable=ReportFiles]$($reportFiles -join ';')"
            }
            else {
              Write-Host "No report.json files changed."
              Write-Host "##vso[task.setvariable variable=ReportFiles]NoFiles"
            }

      # 3) Download PBI Inspector CLI.
      - task: PowerShell@2
        displayName: 'Download PBI Inspector'
        condition: and(succeeded(), ne(variables['ReportFiles'], 'NoFiles'))
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $tempPath = Join-Path $path '_temp'
            $inspectorPath = Join-Path $path '_tools\PBIInspector'
            New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null
            New-Item -ItemType Directory -Path $inspectorPath -ErrorAction SilentlyContinue | Out-Null

            Write-Host "##[debug]Downloading PBI Inspector CLI..."
            $downloadUrl = "https://github.com/NatVanG/PBI-Inspector/releases/latest/download/win-x64-CLI.zip"
            $zipFile = Join-Path $tempPath 'PBIXInspector.zip'
            Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
            Expand-Archive -Path $zipFile -DestinationPath $inspectorPath -Force

      # 4) Set the rule set file path from the repository.
      - task: PowerShell@2
        displayName: 'Set Rule Set File'
        condition: and(succeeded(), ne(variables['ReportFiles'], 'NoFiles'))
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $ruleSetFile = Join-Path $path "pbi_insp_rules\pbi_insp_base_rules.json"
            if (!(Test-Path $ruleSetFile)) {
              Write-Error "Base rule set file not found at $ruleSetFile"
              exit 1
            }
            Write-Host "Using base rule set: $ruleSetFile"
            Write-Host "##vso[task.setvariable variable=RuleSetFile]$ruleSetFile"

      # 5) Run PBI Inspector on each modified report.json file.
      - task: PowerShell@2
        displayName: 'Run Report Rules'
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $toolPath = "$path\_Tools\PBIInspector\win-x64\CLI\PBIXInspectorCLI.exe"
            $rulesPath = "$path\pbi_insp_rules\pbi_insp_base_rules.json"

            if (!(Test-Path $rulesPath)) {
                Write-Error "Base rule set file not found at $rulesPath"
                exit 1
            }

            # Retrieve all .pbir files (if your reports use that extension)
            $itemsFolders = Get-ChildItem -Path $path -Recurse -Include *.pbir

            foreach ($itemFolder in $itemsFolders) {
                $itemPath = $itemFolder.Directory.FullName
                
                Write-Host "##[group]Running rules for: '$itemPath'"
                
                # Run PBI Inspector CLI using the correct rules file
                Start-Process -FilePath $toolPath -ArgumentList "-pbipreport `"$itemPath`" -rules `"$rulesPath`" -formats ADO" -NoNewWindow -Wait
                
                Write-Host "##[endgroup]"
            }
