trigger: none
pr: none

# Reference the variable group
variables:
- group: 'PowerBI-Rules-Paths'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build and Test All Datasets'
  jobs:
  - job: Build_Datasets
    displayName: 'Analyze All Datasets'
    steps:
      - checkout: self
        path: 'self'
        
      - task: PowerShell@2
        displayName: 'Download Tabular Editor'
        inputs:
          targetType: inline
          script: |     
            $path = "$(Build.SourcesDirectory)"                       
            $tempPath = Join-Path $path '_temp'
            $toolPath = Join-Path $path '_tools\TE'
            New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null
            New-Item -ItemType Directory -Path $toolPath -ErrorAction SilentlyContinue | Out-Null
            
            Write-Host "##[debug]Downloading Tabular Editor binaries"
            $downloadUrl = "https://github.com/TabularEditor/TabularEditor/releases/latest/download/TabularEditor.Portable.zip"
            $zipFile = Join-Path $tempPath 'TabularEditor.zip'
            Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
            Expand-Archive -Path $zipFile -DestinationPath $toolPath -Force

      - task: PowerShell@2
        displayName: 'Verify BPA Rules File'
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            # Use the variable from the variable group
            $rulesPath = Join-Path $path "$(te_bpa_standard_rules)"
            
            if (!(Test-Path $rulesPath)) {
              Write-Error "BPA rules file not found at $rulesPath"
              exit 1
            }
            Write-Host "Using BPA rules: $rulesPath"

      - task: PowerShell@2
        displayName: 'Run Dataset Rules on All Models'
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $toolPath = Join-Path $path '_tools\TE\TabularEditor.exe'
            # Use the variable from the variable group
            $rulesPath = Join-Path $path "$(te_bpa_standard_rules)"

            # Find all Power BI dataset/semantic model folders
            $allModelItems = @()
            
            # Find .SemanticModel folders (for .pbip format) - these take priority
            $semanticModelFolders = Get-ChildItem -Path $path -Recurse -Directory -ErrorAction SilentlyContinue | 
                Where-Object { $_.Name -like "*.SemanticModel" }
            
            # Find .pbidataset and .pbism items (could be folders or files)
            $pbidatasetItems = Get-ChildItem -Path $path -Recurse -Include "*.pbidataset" -ErrorAction SilentlyContinue
            $pbismItems = Get-ChildItem -Path $path -Recurse -Include "*.pbism" -ErrorAction SilentlyContinue

            # Filter out .pbidataset and .pbism items that are inside .SemanticModel folders
            foreach ($item in $pbidatasetItems) {
                $isInsideSemanticModel = $false
                foreach ($semFolder in $semanticModelFolders) {
                    if ($item.FullName.StartsWith($semFolder.FullName)) {
                        $isInsideSemanticModel = $true
                        break
                    }
                }
                if (-not $isInsideSemanticModel) {
                    $allModelItems += $item
                }
            }

            foreach ($item in $pbismItems) {
                $isInsideSemanticModel = $false
                foreach ($semFolder in $semanticModelFolders) {
                    if ($item.FullName.StartsWith($semFolder.FullName)) {
                        $isInsideSemanticModel = $true
                        break
                    }
                }
                if (-not $isInsideSemanticModel) {
                    $allModelItems += $item
                }
            }

            # Add .SemanticModel folders
            $allModelItems += $semanticModelFolders

            # Find standalone .bim files (not inside any model folder)
            $bimFiles = Get-ChildItem -Path $path -Recurse -Include "*.bim" -ErrorAction SilentlyContinue
            foreach ($bimFile in $bimFiles) {
                # Check if .bim is inside any model folder
                if ($bimFile.FullName -notmatch '\\(pbidataset|pbism|SemanticModel)\\') {
                    $allModelItems += $bimFile
                }
            }

            if ($allModelItems.Count -eq 0) {
                Write-Host "##[warning]No Power BI models found in the repository."
                exit 0
            }

            Write-Host "##[section]Found $($allModelItems.Count) model(s) to analyze"

            # Arrays to track results
            $passedModels = @()
            $failedModels = @()

            foreach ($item in $allModelItems) {
                $modelName = $item.Name
                $itemPath = $null
                
                # Determine if this is a directory or file
                if ($item.PSIsContainer) {
                    # It's a directory (.pbidataset, .pbism, or .SemanticModel)
                    $modelFolder = $item.FullName
                    
                    # Try TMDL format first (definition folder)
                    $tmdlPath = Join-Path $modelFolder "definition"
                    if (Test-Path $tmdlPath) {
                        $itemPath = $tmdlPath
                    }
                    else {
                        # Fallback to BIM format
                        $bimPath = Join-Path $modelFolder "model.bim"
                        if (Test-Path $bimPath) {
                            $itemPath = $bimPath
                        }
                    }
                    
                    if (-not $itemPath) {
                        Write-Warning "Cannot find model definition (definition folder or model.bim) in $($item.FullName)"
                        continue
                    }
                }
                else {
                    # It's a standalone .bim file
                    $itemPath = $item.FullName
                }

                Write-Host "##[group]Running BPA for: '$modelName'"
                Write-Host "  Model path: $itemPath"

                $process = Start-Process -FilePath $toolPath -ArgumentList """$itemPath"" -A ""$rulesPath"" -V" -NoNewWindow -Wait -PassThru

                if ($process.ExitCode -ne 0) {
                    Write-Host "##[error]BPA validation failed for: $modelName"
                    $failedModels += [PSCustomObject]@{
                        Name = $modelName
                        Path = $itemPath
                    }
                }
                else {
                    Write-Host "##[command]BPA validation passed for: $modelName"
                    $passedModels += [PSCustomObject]@{
                        Name = $modelName
                        Path = $itemPath
                    }
                }

                Write-Host "##[endgroup]"
            }

            # Print summary
            Write-Host ""
            Write-Host "##[section]=========================================="
            Write-Host "##[section]BPA VALIDATION SUMMARY"
            Write-Host "##[section]=========================================="
            Write-Host ""
            Write-Host "Total models analyzed: $($passedModels.Count + $failedModels.Count)"
            Write-Host "Models passed: $($passedModels.Count)"
            Write-Host "Models failed: $($failedModels.Count)"
            Write-Host ""

            if ($passedModels.Count -gt 0) {
                Write-Host "##[section]✓ PASSED MODELS ($($passedModels.Count)):"
                Write-Host "##[section]----------------------------------------"
                foreach ($model in $passedModels) {
                    Write-Host "##[command]  ✓ $($model.Name)" -ForegroundColor Green
                    Write-Host "     Path: $($model.Path)"
                }
                Write-Host ""
            }

            if ($failedModels.Count -gt 0) {
                Write-Host "##[section]✗ FAILED MODELS ($($failedModels.Count)):"
                Write-Host "##[section]----------------------------------------"
                foreach ($model in $failedModels) {
                    Write-Host "##[error]  ✗ $($model.Name)"
                    Write-Host "     Path: $($model.Path)"
                }
                Write-Host ""
            }

            Write-Host "##[section]=========================================="

            if ($failedModels.Count -gt 0) {
                Write-Error "$($failedModels.Count) model(s) failed BPA validation. Please review the errors above."
                exit 1
            }
            else {
                Write-Host "##[command]All models passed BPA validation! 🎉" -ForegroundColor Green
            }