trigger:
  branches:
    exclude:
      - main
  paths:
    include:
      - '**/*.Report/definition/**'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.Report/definition/**'

# Reference your Azure DevOps Library variable group
variables:
  - group: 'PowerBI-Rules-Paths'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build and Inspect Reports'
  jobs:
  - job: Build_Reports
    displayName: 'Inspect Modified Reports'
    steps:
      - checkout: self
        path: 'self'
        persistCredentials: true
        fetchDepth: 0

      - task: PowerShell@2
        displayName: 'Identify modified Power BI reports'
        inputs:
          targetType: inline
          script: |
            cd "$(Build.SourcesDirectory)"
            Write-Host "##[section]Comparing HEAD with origin/main to find changed Power BI reports..."
            
            # Fetch latest to ensure we have up-to-date refs
            git fetch origin main --quiet
            
            # Get changed files - use different approach for PR vs branch push
            if ("$(Build.Reason)" -eq "PullRequest") {
                # For PRs, compare PR source with target
                $changedFiles = git diff --name-only origin/main...HEAD
            } else {
                # For branch pushes, compare with main
                $changedFiles = git diff --name-only origin/main HEAD
            }
            
            # Filter for Power BI report-related files (anything under .Report/definition/)
            $filteredFiles = $changedFiles | Where-Object { 
                $_ -like '*.Report/definition/*'
            }
            
            if ($filteredFiles) {
                Write-Host "##[section]Found modified Power BI report files:"
                $filteredFiles | ForEach-Object { Write-Host " - $_" }
                
                # Extract unique .Report folders
                $reportFolders = @()
                $path = "$(Build.SourcesDirectory)"
                
                foreach ($file in $filteredFiles) {
                    # Extract the .Report folder path
                    if ($file -match '(.+?\.Report)/definition/') {
                        $reportFolder = $matches[1]
                        $fullReportPath = Join-Path $path $reportFolder
                        
                        if ((Test-Path $fullReportPath) -and $reportFolders -notcontains $fullReportPath) {
                            $reportFolders += $fullReportPath
                            Write-Host "  → Will inspect report: $reportFolder"
                        }
                    }
                }
                
                if ($reportFolders.Count -gt 0) {
                    Write-Host "##[section]Total reports to inspect: $($reportFolders.Count)"
                    Write-Host "##vso[task.setvariable variable=ReportFolders]$($reportFolders -join ';')"
                } else {
                    Write-Host "##[warning]Could not identify any valid .Report folders from changed files"
                    Write-Host "##vso[task.setvariable variable=ReportFolders]NoFiles"
                }
            } else {
                Write-Host "No Power BI report files changed."
                Write-Host "##vso[task.setvariable variable=ReportFolders]NoFiles"
            }

      - task: PowerShell@2
        displayName: 'Download PBI Inspector V2'
        condition: and(succeeded(), ne(variables['ReportFolders'], 'NoFiles'))
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $tempPath = Join-Path $path '_temp'
            $inspectorPath = Join-Path $path '_tools\PBIInspector'
            New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null
            New-Item -ItemType Directory -Path $inspectorPath -ErrorAction SilentlyContinue | Out-Null

            Write-Host "##[debug]Downloading PBI Inspector V2 CLI..."
            $downloadUrl = "https://github.com/NatVanG/PBI-InspectorV2/releases/latest/download/win-x64-CLI.zip"
            $zipFile = Join-Path $tempPath 'PBIXInspector.zip'
            Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
            Expand-Archive -Path $zipFile -DestinationPath $inspectorPath -Force

      - task: UseDotNet@2
        displayName: 'Install .NET 8.0 Runtime'
        condition: and(succeeded(), ne(variables['ReportFolders'], 'NoFiles'))
        inputs:
          packageType: 'runtime'
          version: '8.0.x'

      - task: PowerShell@2
        displayName: 'Verify Rule Set File'
        condition: and(succeeded(), ne(variables['ReportFolders'], 'NoFiles'))
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            # Use variable from Azure DevOps Library
            $ruleSetFile = Join-Path $path "$(pbi_insp_v2_standard_rules)"
            if (!(Test-Path $ruleSetFile)) {
              Write-Error "Base rule set file not found at $ruleSetFile"
              exit 1
            }
            Write-Host "Using base rule set: $ruleSetFile"

      - task: PowerShell@2
        displayName: 'Run Report Rules with Detailed Output'
        condition: and(succeeded(), ne(variables['ReportFolders'], 'NoFiles'))
        inputs:
          targetType: inline
          script: |
            $path = "$(Build.SourcesDirectory)"
            $toolPath = Join-Path $path "_tools\PBIInspector\win-x64\CLI\PBIRInspectorCLI.exe"
            # Use variable from Azure DevOps Library
            $rulesPath = Join-Path $path "$(pbi_insp_v2_standard_rules)"
            
            if (!(Test-Path $rulesPath)) {
                Write-Error "Base rule set file not found at $rulesPath"
                exit 1
            }

            if (!(Test-Path $toolPath)) {
                Write-Error "PBI Inspector CLI not found at $toolPath"
                exit 1
            }
            
            $reportFolders = "$(ReportFolders)" -split ';'
            
            if (!$reportFolders -or $reportFolders -eq "NoFiles") {
              Write-Host "No modified report folders to process."
              exit 0
            }
            
            Write-Host "##[section]Inspecting $($reportFolders.Count) modified report(s)"
            Write-Host ""
            
            $failedReports = 0
            $reportIndex = 0
            
            foreach ($reportFolder in $reportFolders) {
                $reportIndex++
                
                if (Test-Path $reportFolder) {
                    $reportName = Split-Path $reportFolder -Leaf
                    
                    Write-Host "##[group][$reportIndex/$($reportFolders.Count)] Inspecting: $reportName"
                    Write-Host "##[section]Report Path: $reportFolder"
                    Write-Host ""
                    
                    # Run PBI Inspector with Console format for detailed output
                    $arguments = "-pbipreport `"$reportFolder`" -rules `"$rulesPath`" -formats Console"
                    Write-Host "##[debug]Executing: $toolPath $arguments"
                    Write-Host ""
                    
                    # Capture output
                    $output = & $toolPath -pbipreport "$reportFolder" -rules "$rulesPath" -formats "Console" 2>&1
                    
                    # Display the output
                    Write-Host "##[section]Inspection Results:"
                    Write-Host "----------------------------------------"
                    $output | ForEach-Object {
                        $line = $_.ToString()
                        
                        # Color code different types of messages
                        if ($line -match "PASS|Passed|✓") {
                            Write-Host "##[debug]$line"
                        }
                        elseif ($line -match "FAIL|Failed|✗|ERROR") {
                            Write-Host "##[error]$line"
                        }
                        elseif ($line -match "WARN|Warning|⚠") {
                            Write-Host "##[warning]$line"
                        }
                        else {
                            Write-Host $line
                        }
                    }
                    Write-Host "----------------------------------------"
                    Write-Host ""
                    
                    # Run again with ADO format for pipeline integration
                    $process = Start-Process -FilePath $toolPath -ArgumentList "-pbipreport `"$reportFolder`" -rules `"$rulesPath`" -formats ADO" -NoNewWindow -Wait -PassThru
                    
                    if ($process.ExitCode -ne 0) {
                        Write-Host "##[error]✗ Validation FAILED for: $reportName"
                        $failedReports++
                    } else {
                        Write-Host "##[section]✓ Validation PASSED for: $reportName"
                    }
                    
                    Write-Host "##[endgroup]"
                    Write-Host ""
                } else {
                    Write-Warning "Report folder not found: $reportFolder"
                }
            }
            
            Write-Host "##[section]================================"
            Write-Host "##[section]Inspection Summary"
            Write-Host "##[section]================================"
            Write-Host "##[section]Total modified reports: $($reportFolders.Count)"
            Write-Host "##[section]Passed: $($reportFolders.Count - $failedReports)"
            Write-Host "##[section]Failed: $failedReports"
            Write-Host "##[section]================================"
            
            if ($failedReports -gt 0) {
                Write-Error "$failedReports report(s) failed validation"
                exit 1
            }